# coding: utf-8
#
# Rakefile
#

if RUBY_PLATFORM =~ /darwin/
  ASTYLE = './Tools/Bin/AStyle'
else
  raise
end

desc 'ドキュメントの作成をする'
task :doc do
  rm_rf 'Doc'
  mkdir_p 'Doc'
  sh 'doxygen'
end

desc 'プログラムに必要な変換を行う'
task :prebuild do
  chdir 'Data' do
    sh 'rake proto'
  end
end

desc '*.csファイルを整形する'
task :format do
  srcs = FileList['Client/Assets/Scripts/**/*.cs']
         .exclude('**/AutoGenerated/**')
         .exclude('**/Vendor/**')
  sh ASTYLE, '--options=.astyle', *srcs
end
