# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/test.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Test.Simple" do
    optional :f, :int32, 1
  end
  add_message "Test.MapTest" do
    map :f, :string, :int32, 1
  end
  add_message "Test.ArrayTest" do
    repeated :f, :int32, 1
  end
end

module Test
  Simple = Google::Protobuf::DescriptorPool.generated_pool.lookup("Test.Simple").msgclass
  MapTest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Test.MapTest").msgclass
  ArrayTest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Test.ArrayTest").msgclass
end
