# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_log.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GameLog.Point" do
    optional :x, :int32, 1
    optional :y, :int32, 2
  end
  add_message "GameLog.DamageInfo" do
    optional :Amount, :int32, 1
  end
  add_message "GameLog.Walk" do
    optional :character_id, :int32, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
    optional :old_x, :int32, 4
    optional :old_y, :int32, 5
    optional :dir, :int32, 6
  end
  add_message "GameLog.WalkMulti" do
    repeated :items, :message, 1, "GameLog.Walk"
  end
  add_message "GameLog.Skill" do
    optional :character_id, :int32, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
    optional :dir, :int32, 4
    optional :skill_id, :string, 5
  end
  add_message "GameLog.Damage" do
    optional :character_id, :int32, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
    optional :dir, :int32, 4
    optional :hp, :int32, 5
    optional :old_hp, :int32, 6
  end
  add_message "GameLog.AnimateCharacter" do
    optional :character_id, :int32, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
    optional :dir, :int32, 4
    optional :animation, :enum, 5, "GameLog.Animation"
  end
  add_message "GameLog.KillCharacter" do
    optional :character_id, :int32, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
  end
  add_message "GameLog.Shutdown" do
  end
  add_message "GameLog.AckResponseRequest" do
  end
  add_message "GameLog.ShutdownRequest" do
  end
  add_message "GameLog.StayRequest" do
  end
  add_message "GameLog.SkillRequest" do
    optional :character_id, :int32, 1
    optional :dir, :int32, 2
    optional :skill_id, :string, 3
  end
  add_message "GameLog.WalkRequest" do
    optional :character_id, :int32, 1
    repeated :path, :message, 2, "GameLog.Point"
  end
  add_message "GameLog.Message" do
    optional :message_id, :string, 1
    repeated :param, :string, 2
  end
  add_enum "GameLog.Animation" do
    value :None, 0
    value :Attack, 1
    value :Damaged, 2
  end
end

module GameLog
  Point = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Point").msgclass
  DamageInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.DamageInfo").msgclass
  Walk = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Walk").msgclass
  WalkMulti = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.WalkMulti").msgclass
  Skill = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Skill").msgclass
  Damage = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Damage").msgclass
  AnimateCharacter = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.AnimateCharacter").msgclass
  KillCharacter = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.KillCharacter").msgclass
  Shutdown = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Shutdown").msgclass
  AckResponseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.AckResponseRequest").msgclass
  ShutdownRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.ShutdownRequest").msgclass
  StayRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.StayRequest").msgclass
  SkillRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.SkillRequest").msgclass
  WalkRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.WalkRequest").msgclass
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Message").msgclass
  Animation = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Animation").enummodule
end
