# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_log.proto

require 'google/protobuf'

require 'master_pb'
require 'game_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GameLog.Point" do
    optional :x, :int32, 1
    optional :y, :int32, 2
  end
  add_message "GameLog.Walk" do
    optional :character_id, :int32, 1
    optional :x, :int32, 2
    optional :y, :int32, 3
    optional :old_x, :int32, 4
    optional :old_y, :int32, 5
    optional :dir, :int32, 6
  end
  add_message "GameLog.WalkMulti" do
    repeated :items, :message, 1, "GameLog.Walk"
  end
  add_message "GameLog.Shutdown" do
  end
  add_message "GameLog.AckResponseRequest" do
  end
  add_message "GameLog.ShutdownRequest" do
  end
  add_message "GameLog.StayRequest" do
  end
  add_message "GameLog.WalkRequest" do
    optional :character_id, :int32, 1
    repeated :path, :message, 2, "GameLog.Point"
  end
end

module GameLog
  Point = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Point").msgclass
  Walk = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Walk").msgclass
  WalkMulti = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.WalkMulti").msgclass
  Shutdown = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Shutdown").msgclass
  AckResponseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.AckResponseRequest").msgclass
  ShutdownRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.ShutdownRequest").msgclass
  StayRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.StayRequest").msgclass
  WalkRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.WalkRequest").msgclass
end
