# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Master.PbxHeader" do
    map :int_index, :int32, :int32, 1
    map :string_index, :string, :int32, 2
  end
  add_message "Master.SpecialScope" do
    optional :type, :enum, 1, "Master.ScopeType"
    optional :target_type, :enum, 2, "Master.ScopeTargetType"
    optional :range, :int32, 3
  end
  add_message "Master.SpecialTemplate" do
    optional :scope, :message, 1, "Master.SpecialScope"
    optional :type, :string, 2
    optional :pow, :int32, 3
    optional :turn, :int32, 4
    optional :amount, :int32, 5
    optional :rand, :int32, 6
    optional :direct, :int32, 7
    optional :prob, :int32, 8
  end
  add_message "Master.Skill" do
    optional :type, :int32, 1
    optional :power, :int32, 2
  end
  add_message "Master.Ability" do
    optional :type, :int32, 1
  end
  add_message "Master.CharacterTemplate" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :image, :int32, 3
    optional :hp, :int32, 4
    optional :attack, :int32, 5
    optional :defense, :int32, 6
  end
  add_message "Master.StageCharacter" do
    optional :x, :int32, 1
    optional :y, :int32, 2
    optional :name, :string, 3
    optional :char, :int32, 6
    optional :character_id, :int32, 4
    optional :speed, :int32, 7
    optional :level, :int32, 5
  end
  add_message "Master.Stage" do
    optional :id, :int32, 1
    optional :width, :int32, 2
    optional :height, :int32, 3
    optional :name, :string, 4
    optional :field_name, :string, 5
    repeated :tiles, :int32, 6
    repeated :characters, :message, 7, "Master.StageCharacter"
  end
  add_enum "Master.ScopeType" do
    value :Self, 0
    value :Straight, 1
    value :Around, 2
  end
  add_enum "Master.ScopeTargetType" do
    value :Both, 0
    value :Ours, 1
    value :Others, 2
  end
end

module Master
  PbxHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.PbxHeader").msgclass
  SpecialScope = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.SpecialScope").msgclass
  SpecialTemplate = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.SpecialTemplate").msgclass
  Skill = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.Skill").msgclass
  Ability = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.Ability").msgclass
  CharacterTemplate = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.CharacterTemplate").msgclass
  StageCharacter = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.StageCharacter").msgclass
  Stage = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.Stage").msgclass
  ScopeType = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.ScopeType").enummodule
  ScopeTargetType = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.ScopeTargetType").enummodule
end
